'use client';

export default function Projects() {
  return (
    <section id="projects" className="py-20 px-4"><div className="max-w-5xl mx-auto"><h2 className="text-3xl font-bold text-white mb-8">Projects</h2><div className="grid md:grid-cols-2 gap-6">
            <div key="Zenflow - Clinical Workflow & Provider Management Dashboard" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Zenflow - Clinical Workflow & Provider Management Dashboard</h3><p className="text-gray-400 mt-2">Architected a comprehensive healthcare provider management SaaS dashboard to significantly optimize clinical workflow efficiency and practitioner coordination. Engineered a low-latency, dynamic weekly scheduling calendar grid capable of flawlessly coordinating simultaneous multi-practitioner time slots and real-time appointment statuses (Ongoing, Pending, Cancelled). Integrated secure operational metrics tables, modular analytics panels, and comprehensive partner-corporate client views for robust practitioner utilization monitoring.</p></div>
            <div key="Solitare - Premium Headless E-Commerce Jewelry Platform" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Solitare - Premium Headless E-Commerce Jewelry Platform</h3><p className="text-gray-400 mt-2">Developed a highly responsive and visually compelling headless e-commerce interface, tailored for immersive luxury catalog interaction and brand discovery. Implemented advanced localized category filters (Bangles, Necklaces, Rings, etc.), persistent client-side states, high-fidelity item grids, and seamless customer favorites/wishlist functionalities. Optimized modern asset delivery networks and lazy-loading mechanisms, achieving a remarkable 35% improvement in First Contentful Paint (FCP) across high-resolution product showcase nodes.</p></div>
            <div key="Pizza – Real-Time Hospitality Outlet Management Application" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Pizza – Real-Time Hospitality Outlet Management Application</h3><p className="text-gray-400 mt-2">Built a tablet-optimized, real-time outlet operations and layout management dashboard designed to minimize operational friction in high-volume dining environments. Engineered an intuitive live floor-plan manager utilizing persistent state updates to accurately map table statuses (Vacant, Occupied, Overdue) with automated alert systems. Established a centralized telemetry pipeline displaying key performance metrics (Average Table Turnaround time and Average Queue Time), successfully lowering seating friction intervals by 18%.</p></div>
            <div key="Trinity – Personalized Mental Health & Wellness Mobile Application" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Trinity – Personalized Mental Health & Wellness Mobile Application</h3><p className="text-gray-400 mt-2">Designed and developed an intuitive, user-centric cross-platform mobile application focused on mental well-being, behavioral habits, and telehealth access. Created a smooth, interactive daily mood journaling module with specialized feedback components and micro-interactions that boosted user retention metrics by 22%. Established secure, encrypted synchronization endpoints for safe user data transmission, self-assessments, and streamlined clinical consultation appointment booking.</p></div>
          </div></div></section>
  );
}
